// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBo33bkpd7xzmLcXGtjpdfiepUAPTRfsrk',
    appId: '1:420582560856:android:e956af324f7e6ad3bc662d',
    messagingSenderId: '420582560856',
    projectId: 'flutter-chat-app-e70d4',
    storageBucket: 'flutter-chat-app-e70d4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApPFm6pEFvXqJ-EFLkFzbGeMQgUzctafY',
    appId: '1:420582560856:ios:ba8471b221f8ef0fbc662d',
    messagingSenderId: '420582560856',
    projectId: 'flutter-chat-app-e70d4',
    storageBucket: 'flutter-chat-app-e70d4.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuaqyEElXPgA0JjP5FZZkIA_bxhra7mao',
    appId: '1:420582560856:web:fbed23856bb099dbbc662d',
    messagingSenderId: '420582560856',
    projectId: 'flutter-chat-app-e70d4',
    authDomain: 'flutter-chat-app-e70d4.firebaseapp.com',
    storageBucket: 'flutter-chat-app-e70d4.appspot.com',
  );

}